### ISSUE TITLE
timer doesnt work

### ISSUE THREAD

**Issue by sunnyBshrestha** [EarnForex/AutoTrading-Scheduler#1]
when trying with new version of mt5 the timer doesnt work
there should a easy option like 
1. Trade in Asian session only
2. Trade in NY session only
3. Trade in London session only
4. Trade in Asian & London session only
5. Trade in London & NY session only
6. Trade in Asian & NY session only

According to broker server time
So that there is no confusion.

**Comment by EarnForex** [comment]
Hello!

Which Build are you using? It works fine in 3091.

As for the sessions, there are two major obstacles:
1. It would be very confusing as there are numerous contradicting sources as to which time ranges to count for which trading session.
2. There is no way to detect broker server's time zone difference with GMT.
